name: aims_college
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  lottie: 3.1.2
  fluttertoast: 8.2.6
  intl: 0.19.0
  font_awesome_flutter: 10.7.0
  carousel_slider: 4.2.1
  get_storage: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/animations/
    - assets/images/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-Regular.ttf
  uses-material-design: true